[tool.ariadne-codegen]
queries_path = "graphql"
remote_schema_url = "https://app.saola.sg/v1/graphql"
remote_schema_headers = {"Authorization" = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJoYXN1cmEiOnsieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJ1c2VyIl0sIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS11c2VyLWlkIjoiMzQyZGI0NDAtMDA4Yy00MTA0LWExZmYtNGYzY2ZjMmRjOTQ1IiwieC1oYXN1cmEtdXNlci1pcy1hbm9ueW1vdXMiOiJmYWxzZSJ9LCJzdWIiOiIzNDJkYjQ0MC0wMDhjLTQxMDQtYTFmZi00ZjNjZmMyZGM5NDUiLCJpYXQiOjE3MTk5MjI0NTAsImV4cCI6MTcyMDAwODg1MCwiaXNzIjoiaGFzdXJhLWF1dGgifQ.NQD_H3Qza_8zpNKcsNxw_ImdhidcpHzy5wNLdL6duDg"}
